export const AVATARS = [
  "Animist",
  "Archimago",
  "Avatar of Air",
  "Avatar of Earth",
  "Avatar of Fire",
  "Avatar of Water",
  "Battlemage",
  "Bladedancer",
  "Corruptor",
  "Deathspeaker",
  "Dragonlord",
  "Druid",
  "Duplicator",
  "Elementalist",
  "Enchantress",
  "Flamecaller",
  "Geomancer",
  "Harbinger",
  "Imposter",
  "Interrogator",
  "Ironclad",
  "Magician",
  "Necromancer",
  "Pathfinder",
  "Persecutor",
  "Realm Eater",
  "Savior",
  "Seer",
  "Sorcerer",
  "Sparkmage",
  "Spellslinger",
  "Templar",
  "Waveshaper",
  "Witch"
] as const;

export function isValidAvatar(value: string): boolean {
  return AVATARS.includes(value as (typeof AVATARS)[number]);
}